services:
  ardupilot-sitl:
    image: radarku/ardupilot-sitl
    platform: "linux/amd64"
    container_name: sitl
    ports:
      - "5760:5760"
    restart: 'always'
  rust-dev:
    build:
      context: ./docker
      dockerfile: rust-dev.Dockerfile
    volumes:
      - .:/dev:cached
      - ./target:/dev/target
      - /var/run/docker.sock:/var/run/docker.sock
      # bash history
      - ~/.bash_history:/root/.bash_history
      # Optionally the zshrc
      - ~/.zshrc:/root/.zshrc
    working_dir: /dev
    container_name: rust-dev
    stdin_open: true
    # bind to host network
    network_mode: host
    # 
    tty: true
