services:
  ardupilot-sitl:
    image: radarku/ardupilot-sitl
    platform: "linux/amd64"
    container_name: sitl
    ports:
      - "5760:5760"
    restart: 'always'
  lil-interface:
    image: lil-interface
    container_name: ui
    build:
      context: ./lil-interface
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    restart: 'always'
  rust-dev:
    build:
      context: ./docker
      dockerfile: rust-dev.Dockerfile
    volumes:
      - .:/lil-dev:cached
      - ./target:/lil-dev/target
      - /var/run/docker.sock:/var/run/docker.sock
      # bash history
      - ~/.bash_history:/root/.bash_history
    working_dir: /lil-dev
    container_name: rust-dev
    stdin_open: true
    # bind to host network
    network_mode: host
    # 
    tty: true
