version: '3'

services:
  ardupilot-sitl:
    image: radarku/ardupilot-sitl
    platform: "linux/amd64" # macos AMD has the wrong architecture
    container_name: sitl
    ports:
      - "5760:5760"
    restart: 'always'
  lil-interface:
    image: lil-interface
    container_name: ui
    build:
      context: ./lil-interface
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    restart: 'always'