(function() {var implementors = {
"async_fs":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.74.1/std/os/fd/raw/trait.AsRawFd.html\" title=\"trait std::os::fd::raw::AsRawFd\">AsRawFd</a> for <a class=\"struct\" href=\"async_fs/struct.File.html\" title=\"struct async_fs::File\">File</a>"]],
"async_io":[["impl&lt;T: <a class=\"trait\" href=\"https://doc.rust-lang.org/1.74.1/std/os/fd/raw/trait.AsRawFd.html\" title=\"trait std::os::fd::raw::AsRawFd\">AsRawFd</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/1.74.1/std/os/fd/raw/trait.AsRawFd.html\" title=\"trait std::os::fd::raw::AsRawFd\">AsRawFd</a> for <a class=\"struct\" href=\"async_io/struct.Async.html\" title=\"struct async_io::Async\">Async</a>&lt;T&gt;"]],
"mio":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.74.1/std/os/fd/raw/trait.AsRawFd.html\" title=\"trait std::os::fd::raw::AsRawFd\">AsRawFd</a> for <a class=\"struct\" href=\"mio/unix/pipe/struct.Sender.html\" title=\"struct mio::unix::pipe::Sender\">Sender</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.74.1/std/os/fd/raw/trait.AsRawFd.html\" title=\"trait std::os::fd::raw::AsRawFd\">AsRawFd</a> for <a class=\"struct\" href=\"mio/struct.Registry.html\" title=\"struct mio::Registry\">Registry</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.74.1/std/os/fd/raw/trait.AsRawFd.html\" title=\"trait std::os::fd::raw::AsRawFd\">AsRawFd</a> for <a class=\"struct\" href=\"mio/unix/pipe/struct.Receiver.html\" title=\"struct mio::unix::pipe::Receiver\">Receiver</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.74.1/std/os/fd/raw/trait.AsRawFd.html\" title=\"trait std::os::fd::raw::AsRawFd\">AsRawFd</a> for <a class=\"struct\" href=\"mio/struct.Poll.html\" title=\"struct mio::Poll\">Poll</a>"]],
"nix":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.74.1/std/os/fd/raw/trait.AsRawFd.html\" title=\"trait std::os::fd::raw::AsRawFd\">AsRawFd</a> for <a class=\"struct\" href=\"nix/poll/struct.PollFd.html\" title=\"struct nix::poll::PollFd\">PollFd</a>"]],
"polling":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.74.1/std/os/fd/raw/trait.AsRawFd.html\" title=\"trait std::os::fd::raw::AsRawFd\">AsRawFd</a> for <a class=\"struct\" href=\"polling/struct.Poller.html\" title=\"struct polling::Poller\">Poller</a>"]],
"rustix":[],
"smithay_client_toolkit":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.74.1/std/os/fd/raw/trait.AsRawFd.html\" title=\"trait std::os::fd::raw::AsRawFd\">AsRawFd</a> for <a class=\"struct\" href=\"smithay_client_toolkit/data_device/struct.ReadPipe.html\" title=\"struct smithay_client_toolkit::data_device::ReadPipe\">ReadPipe</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.74.1/std/os/fd/raw/trait.AsRawFd.html\" title=\"trait std::os::fd::raw::AsRawFd\">AsRawFd</a> for <a class=\"struct\" href=\"smithay_client_toolkit/data_device/struct.WritePipe.html\" title=\"struct smithay_client_toolkit::data_device::WritePipe\">WritePipe</a>"]],
"socket2":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.74.1/std/os/fd/raw/trait.AsRawFd.html\" title=\"trait std::os::fd::raw::AsRawFd\">AsRawFd</a> for <a class=\"struct\" href=\"socket2/struct.Socket.html\" title=\"struct socket2::Socket\">Socket</a>"]],
"wayland_commons":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.74.1/std/os/fd/raw/trait.AsRawFd.html\" title=\"trait std::os::fd::raw::AsRawFd\">AsRawFd</a> for <a class=\"struct\" href=\"wayland_commons/socket/struct.Socket.html\" title=\"struct wayland_commons::socket::Socket\">Socket</a>"]],
"x11rb":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.74.1/std/os/fd/raw/trait.AsRawFd.html\" title=\"trait std::os::fd::raw::AsRawFd\">AsRawFd</a> for <a class=\"struct\" href=\"x11rb/rust_connection/struct.DefaultStream.html\" title=\"struct x11rb::rust_connection::DefaultStream\">DefaultStream</a>"]],
"x11rb_protocol":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.74.1/std/os/fd/raw/trait.AsRawFd.html\" title=\"trait std::os::fd::raw::AsRawFd\">AsRawFd</a> for <a class=\"struct\" href=\"x11rb_protocol/struct.RawFdContainer.html\" title=\"struct x11rb_protocol::RawFdContainer\">RawFdContainer</a>"]],
"zvariant":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.74.1/std/os/fd/raw/trait.AsRawFd.html\" title=\"trait std::os::fd::raw::AsRawFd\">AsRawFd</a> for <a class=\"struct\" href=\"zvariant/struct.OwnedFd.html\" title=\"struct zvariant::OwnedFd\">OwnedFd</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/1.74.1/std/os/fd/raw/trait.AsRawFd.html\" title=\"trait std::os::fd::raw::AsRawFd\">AsRawFd</a> for <a class=\"struct\" href=\"zvariant/struct.Fd.html\" title=\"struct zvariant::Fd\">Fd</a>"]]
};if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()