[patch.crates-io]
victory-commander = { path = "victory-suite/victory-commander" }
victory-data-store = { path = "victory-suite/victory-data-store" }
victory-wtf = { path = "victory-suite/victory-wtf" } 