name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/install-action@nextest
      - uses: actions/checkout@v4
      - name: Install Rust
        run: rustup update stable
      - name: Install cargo-llvm-cov
        run: cargo +stable install cargo-llvm-cov --locked
      - name: Build
        run: cargo build --verbose  
      - name: Run tests
        run: cargo nextest run --verbose
      - name: Generate code coverage
        run: cargo llvm-cov --all-features --workspace --codecov --output-path codecov.json
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
            files: codecov.json
            fail_ci_if_error: true 
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/install-action@nextest
      - uses: actions/checkout@v4
      - name: Install Rust
        run: rustup update stable
      - name: Build docs
        run: cargo doc --verbose --all-features --workspace
      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./target/doc